export const INITIAL_SPEECH_TIMEOUT_MS = 5000;

export const SETUP_SILENCE_AFTER_SPEECH_MS = 1000;
export const SETUP_MAXIMUM_RECORDING_MS = 15000;

export const ANSWER_SILENCE_AFTER_SPEECH_MS = 2000;
export const ANSWER_MAXIMUM_RECORDING_MS = 30000;

export const SPEECH_LEVEL_THRESHOLD = 0.02;
