export const SONGS_PER_PLAYER = 5;
export const MIN_SONGS_PER_PLAYER = 3;
export const MAX_SONGS_PER_PLAYER = 20;
export const SONG_GENERATION_BUFFER_MULTIPLIER = 1.25;

export const MIN_PLAYABLE_DURATION_SECONDS = 120;
export const MAX_PLAYABLE_DURATION_SECONDS = 420;

export const CLIP_DURATION_SECONDS = 20;
export const LONG_VIDEO_THRESHOLD_SECONDS = 300;
export const LONG_VIDEO_MIN_START_OFFSET_SECONDS = 90;

export const MIN_HUNGARIAN_SONG_RATIO = 0.15;
export const MAX_HUNGARIAN_SONG_RATIO = 0.35;
